[FEAT] Combined repositories screen with the workflow screen
sahilrohera10/PullMate pull request #39
Opened 2024-11-27 14:41 UTC by YASH-RAJ-HANS

-> Pagination is working.
-> Repos are fetched in latest push manner 
-> all repos are fetched including cross owner and organization public one
-> Combined repositories screen with the workflow screen

![image](https://github.com/user-attachments/assets/b8d9acff-b6ed-44d4-9b2e-0b77039eff40)
![image](https://github.com/user-attachments/assets/78547b23-54a4-4cf0-af51-19de949c48c6)
![image](https://github.com/user-attachments/assets/46604cc4-d800-4bc2-bb2f-12ca238385e2)

![image](https://github.com/user-attachments/assets/2a7de8ac-4003-48d0-bb44-29c9cd52efe5)

2024-11-27 16:09 UTC, sahilarora02 commented on server/src/controllers/github.controller.ts
> +    console.log("repo body",response.data);
Try to use logger now

Also use it while development ,remove them while pushing to git

(unless its important)

2024-11-27 16:10 UTC, sahilarora02 commented on server/src/controllers/github.controller.ts
> +  const { type = "all", sort = "pushed", direction = "desc", per_page = 20, page = 1 } = req.body;
why per_page is not 30??
i though 30 was default !!?

2024-11-29 05:54 UTC, sahilrohera10 requested changes

2024-11-29 05:54 UTC, sahilrohera10 commented on client/my-app/src/app/repositories/page.tsx
> +      const fetchRepos = async () => {
this check should be on function call not on function definition

2024-11-29 05:54 UTC, sahilrohera10 commented on client/my-app/src/components/UserRepoTable.tsx
> +          <TableRow
add repo interface here

2024-11-29 05:54 UTC, sahilrohera10 commented on client/my-app/src/components/Workflow.tsx
> +  repo_url: string | null;
take access_token from local storage

dont pass repo_url as props .. take repo_url from url params

2024-11-29 05:54 UTC, sahilrohera10 commented on client/my-app/src/components/Workflow.tsx
> +
take repo_url in this way

2024-11-29 05:54 UTC, sahilrohera10 commented on client/my-app/src/components/Workflow.tsx
> +    try {
remove consoles

2024-11-29 05:54 UTC, sahilrohera10 commented on client/my-app/src/components/Workflow.tsx
> +
why searchParams is in the dependency array ..

rather " const repoUrlFromQuery = searchParams.get("repo"); " should come outside the useEffect and " repoUrlFromQuery " should come in the dependency array...

here is the reason bcz ... everytime when the repoUrlFromQuery changes then we need to run the useEffect

2024-11-29 08:51 UTC, YASH-RAJ-HANS commented on client/my-app/src/components/UserRepoTable.tsx
> +          <TableRow
done

2024-11-29 09:31 UTC, sahilrohera10 approved these changes

2024-11-29 09:37 UTC, merged